In [1]:
import pymongo
import pandas as pd
from bson import ObjectId
from pymongo import MongoClient
import numpy as np

In [2]:

connection_string = f"mongodb+srv://data_science:IEEv1SqNUG5olqqQ@cluster1.iohtk.mongodb.net/strapi-admin-panel?authSource=admin&replicaSet=atlas-h4htax-shard-0&w=majority&readPreference=primary&retryWrites=true&ssl=true"

client = MongoClient(connection_string)

db = client['strapi-admin-panel']
collection = db['basic_analyses']

In [3]:
reql= [ObjectId('62c5cffe3a1ecea908c68050'), ObjectId('62c5cffe3a1ecea908c6804d'), ObjectId('62c5cffe3a1ecea908c68052'), ObjectId('62c5cffe3a1ecea908c68054'), ObjectId('62c5cffe3a1ecea908c68056'), ObjectId('62c5d046dc4ddbc8f155c99f'), ObjectId('62c5d046dc4ddbc8f155c9a1'), ObjectId('62c5d046dc4ddbc8f155c99b'), ObjectId('62c5d046dc4ddbc8f155c99d'), ObjectId('62c5d046dc4ddbc8f155c9aa'), ObjectId('62c5d046dc4ddbc8f155c9a6'), ObjectId('62c5d046dc4ddbc8f155c9ac'), ObjectId('62c5d046dc4ddbc8f155c9a8'), ObjectId('62c5d046dc4ddbc8f155c9ae'), ObjectId('62c5d046dc4ddbc8f155c9b0'), ObjectId('62c5d046dc4ddbc8f155c9b2'), ObjectId('62c5d046dc4ddbc8f155c9b4'), ObjectId('62c5d046dc4ddbc8f155c9b6'), ObjectId('62c5d046dc4ddbc8f155c9bc'), ObjectId('62c5d046dc4ddbc8f155c9b8'), ObjectId('62c5d046dc4ddbc8f155c9ba'), ObjectId('62c5d046dc4ddbc8f155c9c0'), ObjectId('62c5d046dc4ddbc8f155c9c2'), ObjectId('62c5d046dc4ddbc8f155c9be'), ObjectId('62c5d046dc4ddbc8f155c9c6'), ObjectId('62c5d046dc4ddbc8f155c9c4'), ObjectId('62c5d046dc4ddbc8f155c9c8'), ObjectId('62c5d046dc4ddbc8f155c9cc'), ObjectId('62c5d046dc4ddbc8f155c9ce'), ObjectId('62c5d046dc4ddbc8f155c9ca'), ObjectId('62c5d0a66bc2d5ba701abb5b'), ObjectId('62c5d0a66bc2d5ba701abb5f'), ObjectId('62c5d0a66bc2d5ba701abb5d'), ObjectId('62c5d0a66bc2d5ba701abb68'), ObjectId('62c5d0a66bc2d5ba701abb6a'), ObjectId('62c5d0a66bc2d5ba701abb6c'), ObjectId('62c5d0a66bc2d5ba701abb6e'), ObjectId('62c5d0a66bc2d5ba701abb66'), ObjectId('62c5d0a66bc2d5ba701abb70'), ObjectId('62c5d0a66bc2d5ba701abb72'), ObjectId('62c5d0a66bc2d5ba701abb74'), ObjectId('62c5d0a66bc2d5ba701abb78'), ObjectId('62c5d0a66bc2d5ba701abb7e'), ObjectId('62c5d0a66bc2d5ba701abb80'), ObjectId('62c5d0a66bc2d5ba701abb86'), ObjectId('62c5d0a66bc2d5ba701abb84'), ObjectId('62c5d0a66bc2d5ba701abb7a'), ObjectId('62c5d0a66bc2d5ba701abb76'), ObjectId('62c5d0a66bc2d5ba701abb88'), ObjectId('62c5d0a66bc2d5ba701abb7c'), ObjectId('62c5d0a66bc2d5ba701abb82'), ObjectId('62c5d0a66bc2d5ba701abb8a'), ObjectId('62c5d0a66bc2d5ba701abb8c'), ObjectId('62c5d0a66bc2d5ba701abb8e'), ObjectId('62c5d0a66bc2d5ba701abb9a'), ObjectId('62c5d0a66bc2d5ba701abb94'), ObjectId('62c5d0a66bc2d5ba701abb92'), ObjectId('62c5d0a66bc2d5ba701abb90'), ObjectId('62c5d0a66bc2d5ba701abb98'), ObjectId('62c5d0a66bc2d5ba701abb96'), ObjectId('62c5d0a66bc2d5ba701abb9c'), ObjectId('62c5d0a66bc2d5ba701abb9e'), ObjectId('62c5d0a66bc2d5ba701abba0'), ObjectId('62c5d0a66bc2d5ba701abba2'), ObjectId('62c5d0a66bc2d5ba701abba4'), ObjectId('62c5d0a66bc2d5ba701abba8'), ObjectId('62c5d0a66bc2d5ba701abbac'), ObjectId('62c5d0a66bc2d5ba701abbaa'), ObjectId('62c5d0a66bc2d5ba701abba6'), ObjectId('62c5d0a66bc2d5ba701abbb4'), ObjectId('62c5d0a66bc2d5ba701abbb0'), ObjectId('62c5d0a66bc2d5ba701abbae'), ObjectId('62c5d0a66bc2d5ba701abbb2'), ObjectId('62c5d0a66bc2d5ba701abbbe'), ObjectId('62c5d0a66bc2d5ba701abbbc'), ObjectId('62c5d0a66bc2d5ba701abbb6'), ObjectId('62c5d0a66bc2d5ba701abbc0'), ObjectId('62c5d0a66bc2d5ba701abbc2'), ObjectId('62c5d0a66bc2d5ba701abbba'), ObjectId('62c5d0a66bc2d5ba701abbb8'), ObjectId('62c5d0a66bc2d5ba701abbc4'), ObjectId('62c5d0a66bc2d5ba701abbc8'), ObjectId('62c5d0a66bc2d5ba701abbc6'), ObjectId('62c5d0a66bc2d5ba701abbca'), ObjectId('62c94a36288d91c862f1722b'), ObjectId('62c94a36288d91c862f1722f'), ObjectId('62c94a36288d91c862f1722d'), ObjectId('62c94a36288d91c862f17231'), ObjectId('62c94a36288d91c862f17233'), ObjectId('630ce5a52fd4cbcf2b9b509c'), ObjectId('630ce5a52fd4cbcf2b9b50a2'), ObjectId('630ce5a52fd4cbcf2b9b50a4'), ObjectId('630ce5a52fd4cbcf2b9b50a6'), ObjectId('630ce5a52fd4cbcf2b9b50a8'), ObjectId('630ce5a52fd4cbcf2b9b50aa'), ObjectId('630ce5a52fd4cbcf2b9b50ac'), ObjectId('630ce5a52fd4cbcf2b9b50ae'), ObjectId('630ce5a52fd4cbcf2b9b50b0'), ObjectId('630ce5a52fd4cbcf2b9b50b2'), ObjectId('630ce5a52fd4cbcf2b9b50b4'), ObjectId('630ce5a52fd4cbcf2b9b50b6'), ObjectId('630ce5a52fd4cbcf2b9b50b8'), ObjectId('630ce5a52fd4cbcf2b9b50ba'), ObjectId('630ce5a52fd4cbcf2b9b50bc'), ObjectId('630ce5a52fd4cbcf2b9b50be'), ObjectId('630ce5a52fd4cbcf2b9b50c2'), ObjectId('630ce5a52fd4cbcf2b9b50c0'), ObjectId('630ce5a52fd4cbcf2b9b50c6'), ObjectId('630ce5a52fd4cbcf2b9b50c8'), ObjectId('630ce5a52fd4cbcf2b9b50c4'), ObjectId('630ce5a52fd4cbcf2b9b50ca'), ObjectId('630ce5a62fd4cbcf2b9b50cc'), ObjectId('630ce5a62fd4cbcf2b9b50ce'), ObjectId('630ce5a62fd4cbcf2b9b50d0'), ObjectId('630ce5a62fd4cbcf2b9b50d2'), ObjectId('630ce5a62fd4cbcf2b9b50d4'), ObjectId('630ce5a62fd4cbcf2b9b50d6'), ObjectId('630ce5a62fd4cbcf2b9b50d8'), ObjectId('630ce5a62fd4cbcf2b9b50da'), ObjectId('630ce5a62fd4cbcf2b9b50de'), ObjectId('630ce5a62fd4cbcf2b9b50dc'), ObjectId('630ce5a62fd4cbcf2b9b50e2'), ObjectId('630ce5a62fd4cbcf2b9b50e0'), ObjectId('630ce5a62fd4cbcf2b9b50e4'), ObjectId('630ce5a62fd4cbcf2b9b50e6'), ObjectId('630ce5a62fd4cbcf2b9b50e8'), ObjectId('630ce5a62fd4cbcf2b9b50ec'), ObjectId('630ce5a62fd4cbcf2b9b50ea'), ObjectId('630ce5a62fd4cbcf2b9b50ee'), ObjectId('630ce5a62fd4cbcf2b9b50f0'), ObjectId('630ce5a62fd4cbcf2b9b50f2'), ObjectId('630ce5a62fd4cbcf2b9b50f4'), ObjectId('630ce5a62fd4cbcf2b9b50f6'), ObjectId('630ce5a62fd4cbcf2b9b50f8'), ObjectId('630ce5a62fd4cbcf2b9b50fa'), ObjectId('630ce5a62fd4cbcf2b9b50fc'), ObjectId('630ce5a62fd4cbcf2b9b50fe'), ObjectId('630ce5a62fd4cbcf2b9b5100'), ObjectId('630ce5a62fd4cbcf2b9b5102'), ObjectId('630ce5a62fd4cbcf2b9b5104'), ObjectId('630ce5a62fd4cbcf2b9b5106'), ObjectId('630ce5a62fd4cbcf2b9b5108'), ObjectId('630ce5a62fd4cbcf2b9b510a'), ObjectId('630ce5a62fd4cbcf2b9b510c'), ObjectId('630ce5a62fd4cbcf2b9b510e'), ObjectId('630ce5a62fd4cbcf2b9b5110'), ObjectId('630ce5a62fd4cbcf2b9b5112'), ObjectId('630ce5a62fd4cbcf2b9b5114'), ObjectId('630ce5a62fd4cbcf2b9b5116'), ObjectId('630ce5a62fd4cbcf2b9b5118'), ObjectId('630ce5a62fd4cbcf2b9b511a'), ObjectId('630ce5a62fd4cbcf2b9b511c'), ObjectId('630ce5a62fd4cbcf2b9b511e'), ObjectId('630ce5a62fd4cbcf2b9b5120'), ObjectId('630ce5a62fd4cbcf2b9b5124'), ObjectId('630ce5a62fd4cbcf2b9b5122'), ObjectId('630ce5a62fd4cbcf2b9b5126'), ObjectId('630ce5a62fd4cbcf2b9b5128'), ObjectId('630ce5a62fd4cbcf2b9b512a'), ObjectId('630ce5a62fd4cbcf2b9b512c'), ObjectId('630ce5a62fd4cbcf2b9b512e'), ObjectId('630ce5a62fd4cbcf2b9b5130'), ObjectId('630ce5a62fd4cbcf2b9b5132'), ObjectId('630ce5a62fd4cbcf2b9b5134'), ObjectId('630ce5a62fd4cbcf2b9b5136'), ObjectId('630ce5a62fd4cbcf2b9b5138'), ObjectId('630ce5a62fd4cbcf2b9b513a'), ObjectId('630ce5a62fd4cbcf2b9b513c'), ObjectId('630ce5a62fd4cbcf2b9b513e'), ObjectId('63752dd739117e2a799ab9d3'), ObjectId('63752e1739117e2a799ab9d4'), ObjectId('63ea98a967de86a1a7466728'), ObjectId('63ea9c7767de86a1a746672f'), ObjectId('63ea9c7767de86a1a746672e'), ObjectId('63ea9c7767de86a1a7466730'), ObjectId('63ea9c7767de86a1a7466731'), ObjectId('63ea9c7767de86a1a7466732'), ObjectId('63ea9c7767de86a1a7466733'), ObjectId('63ea9c7767de86a1a7466734'), ObjectId('63ea9c7767de86a1a7466735'), ObjectId('63ea9c7767de86a1a7466736'), ObjectId('63ea9c7767de86a1a7466737'), ObjectId('63ea9c7767de86a1a7466738'), ObjectId('637f62157f1e1d0c28041285'), ObjectId('637f63087f1e1d0c28041286'), ObjectId('63806e9b1a459792920d8f15'), ObjectId('6415627ff5e42d88254a20b4'), ObjectId('6415627ff5e42d88254a20b5'), ObjectId('6415627ff5e42d88254a20b6'), ObjectId('6415627ff5e42d88254a20b7'), ObjectId('6415627ff5e42d88254a20b8'), ObjectId('6415627ff5e42d88254a20b9'), ObjectId('6415627ff5e42d88254a20ba'), ObjectId('6415627ff5e42d88254a20bb'), ObjectId('6415627ff5e42d88254a20bc'), ObjectId('6415627ff5e42d88254a20bd'), ObjectId('6415627ff5e42d88254a20be'), ObjectId('6415627ff5e42d88254a20bf'), ObjectId('6415627ff5e42d88254a20c0'), ObjectId('64156280f5e42d88254a20c1'), ObjectId('64156280f5e42d88254a20c2'), ObjectId('64156280f5e42d88254a20c3'), ObjectId('64156280f5e42d88254a20c4'), ObjectId('64156280f5e42d88254a20c5'), ObjectId('64156280f5e42d88254a20c6'), ObjectId('64156280f5e42d88254a20c7'), ObjectId('64156280f5e42d88254a20c8'), ObjectId('64156280f5e42d88254a20c9'), ObjectId('64156280f5e42d88254a20ca'), ObjectId('64156280f5e42d88254a20cb'), ObjectId('64156280f5e42d88254a20cc'), ObjectId('64156280f5e42d88254a20cd'), ObjectId('64156281f5e42d88254a20ce'), ObjectId('64156281f5e42d88254a20cf'), ObjectId('64156281f5e42d88254a20d0'), ObjectId('64156281f5e42d88254a20d1'), ObjectId('64156281f5e42d88254a20d2'), ObjectId('64156281f5e42d88254a20d3'), ObjectId('64156281f5e42d88254a20d4'), ObjectId('64156281f5e42d88254a20d5'), ObjectId('64156281f5e42d88254a20d6'), ObjectId('64156281f5e42d88254a20d7'), ObjectId('64156281f5e42d88254a20d8'), ObjectId('64156281f5e42d88254a20d9'), ObjectId('64156281f5e42d88254a20da'), ObjectId('64156282f5e42d88254a20db'), ObjectId('64156282f5e42d88254a20dc'), ObjectId('64156282f5e42d88254a20dd'), ObjectId('64156282f5e42d88254a20de'), ObjectId('64156282f5e42d88254a20df'), ObjectId('64156282f5e42d88254a20e0'), ObjectId('64156282f5e42d88254a20e1'), ObjectId('64156282f5e42d88254a20e2'), ObjectId('64156282f5e42d88254a20e3'), ObjectId('64156282f5e42d88254a20e4'), ObjectId('64156282f5e42d88254a20e5'), ObjectId('64156282f5e42d88254a20e6'), ObjectId('64156282f5e42d88254a20e7'), ObjectId('64156283f5e42d88254a20e8'), ObjectId('64156283f5e42d88254a20e9'), ObjectId('64156283f5e42d88254a20ea'), ObjectId('64156283f5e42d88254a20eb'), ObjectId('64156283f5e42d88254a20ec'), ObjectId('64156283f5e42d88254a20ed'), ObjectId('64156283f5e42d88254a20ee'), ObjectId('64156283f5e42d88254a20ef'), ObjectId('64156283f5e42d88254a20f0'), ObjectId('64156283f5e42d88254a20f1'), ObjectId('64156283f5e42d88254a20f2'), ObjectId('64156283f5e42d88254a20f3'), ObjectId('64156283f5e42d88254a20f4'), ObjectId('64156284f5e42d88254a20f5'), ObjectId('64156284f5e42d88254a20f6'), ObjectId('64156284f5e42d88254a20f7'), ObjectId('64156284f5e42d88254a20f8'), ObjectId('64156284f5e42d88254a20f9'), ObjectId('64156284f5e42d88254a20fa'), ObjectId('64156284f5e42d88254a20fb'), ObjectId('64156284f5e42d88254a20fc'), ObjectId('64156284f5e42d88254a20fd'), ObjectId('64156284f5e42d88254a20fe'), ObjectId('64156284f5e42d88254a20ff'), ObjectId('64156284f5e42d88254a2100'), ObjectId('64156284f5e42d88254a2101'), ObjectId('64156285f5e42d88254a2102'), ObjectId('64156285f5e42d88254a2103'), ObjectId('64156285f5e42d88254a2104'), ObjectId('64156285f5e42d88254a2105'), ObjectId('64156285f5e42d88254a2106'), ObjectId('64156285f5e42d88254a2107'), ObjectId('64156285f5e42d88254a2108'), ObjectId('64156285f5e42d88254a2109'), ObjectId('64156285f5e42d88254a210a'), ObjectId('64156285f5e42d88254a210b'), ObjectId('64156285f5e42d88254a210c'), ObjectId('64156285f5e42d88254a210d'), ObjectId('64156285f5e42d88254a210e'), ObjectId('64156286f5e42d88254a210f'), ObjectId('6415889fba53754de28c88e3'), ObjectId('6415889fba53754de28c88e5'), ObjectId('6415889fba53754de28c88e7'), ObjectId('6415889fba53754de28c88e9'), ObjectId('6415889fba53754de28c88eb'), ObjectId('6415889fba53754de28c88ed'), ObjectId('6415889fba53754de28c88ef'), ObjectId('6415889fba53754de28c88f1'), ObjectId('641588b7ba53754de28c892f'), ObjectId('641588b7ba53754de28c8933'), ObjectId('641588b7ba53754de28c8935'), ObjectId('641588b7ba53754de28c8937'), ObjectId('641588b7ba53754de28c8939'), ObjectId('641588b7ba53754de28c893b'), ObjectId('641588b7ba53754de28c893d'), ObjectId('641588b7ba53754de28c893f'), ObjectId('641588b7ba53754de28c8941'), ObjectId('641588b7ba53754de28c8943'), ObjectId('641588b7ba53754de28c8945'), ObjectId('641588b7ba53754de28c8947'), ObjectId('641588b7ba53754de28c8949'), ObjectId('641588b7ba53754de28c894b'), ObjectId('641588b7ba53754de28c8951'), ObjectId('641588b7ba53754de28c894f'), ObjectId('641588b7ba53754de28c894d'), ObjectId('641588b7ba53754de28c8953'), ObjectId('641588b7ba53754de28c8955'), ObjectId('641588b7ba53754de28c8957'), ObjectId('641588b7ba53754de28c895b'), ObjectId('641588b7ba53754de28c895d'), ObjectId('641588b7ba53754de28c8959'), ObjectId('641588b7ba53754de28c895f'), ObjectId('641588b7ba53754de28c8961'), ObjectId('641588b7ba53754de28c8963'), ObjectId('641588b7ba53754de28c8965'), ObjectId('641588b7ba53754de28c8967'), ObjectId('641588b7ba53754de28c8969'), ObjectId('641588b7ba53754de28c896b'), ObjectId('64889a1d8be547b3b654cd43'), ObjectId('64889a1d8be547b3b654cd45'), ObjectId('64889a1d8be547b3b654cd47'), ObjectId('64889a1d8be547b3b654cd49'), ObjectId('64889a1d8be547b3b654cd4b'), ObjectId('64889a1d8be547b3b654cd4d'), ObjectId('64889a1d8be547b3b654cd4f'), ObjectId('64889a1d8be547b3b654cd51'), ObjectId('64889a1d8be547b3b654cd55'), ObjectId('64889a1d8be547b3b654cd53'), ObjectId('64889a1d8be547b3b654cd57'), ObjectId('64889a1d8be547b3b654cd59'), ObjectId('6543992fab9f13e68aa06a90'), ObjectId('6543992fab9f13e68aa06a92'), ObjectId('6543992fab9f13e68aa06a94'), ObjectId('6543992fab9f13e68aa06a96'), ObjectId('6543992fab9f13e68aa06a98'), ObjectId('6543992fab9f13e68aa06a9a'), ObjectId('6543992fab9f13e68aa06a9c'), ObjectId('6543992fab9f13e68aa06a9e'), ObjectId('654b8e929d16bb169cf1c038'), ObjectId('654b8e929d16bb169cf1c03a'), ObjectId('654b8e929d16bb169cf1c03c'), ObjectId('654b8e929d16bb169cf1c03e'), ObjectId('654b8e929d16bb169cf1c040'), ObjectId('654b8e929d16bb169cf1c042'), ObjectId('654b8e929d16bb169cf1c046'), ObjectId('654b8e929d16bb169cf1c048'), ObjectId('654b8e929d16bb169cf1c04a'), ObjectId('654b8e929d16bb169cf1c04c'), ObjectId('654b8e929d16bb169cf1c04e'), ObjectId('654b8e929d16bb169cf1c050'), ObjectId('654b8e929d16bb169cf1c052'), ObjectId('654b8e929d16bb169cf1c054'), ObjectId('654b8e929d16bb169cf1c056'), ObjectId('654b8e929d16bb169cf1c058'), ObjectId('654b8e929d16bb169cf1c05a'), ObjectId('654b8e929d16bb169cf1c05c'), ObjectId('654b8e929d16bb169cf1c05e'), ObjectId('654b8e929d16bb169cf1c064'), ObjectId('654b8e929d16bb169cf1c060'), ObjectId('654b8e929d16bb169cf1c062'), ObjectId('654b8e929d16bb169cf1c066'), ObjectId('654b8e929d16bb169cf1c06c'), ObjectId('654b8e929d16bb169cf1c06a'), ObjectId('654b8e929d16bb169cf1c068'), ObjectId('654b8e929d16bb169cf1c06e'), ObjectId('654b8e929d16bb169cf1c070'), ObjectId('654b8e929d16bb169cf1c072'), ObjectId('654b8e929d16bb169cf1c076'), ObjectId('654b8e929d16bb169cf1c074'), ObjectId('654b8e929d16bb169cf1c078'), ObjectId('654b8e929d16bb169cf1c07a'), ObjectId('654b8e929d16bb169cf1c07c'), ObjectId('654b8e929d16bb169cf1c07e'), ObjectId('654b8e929d16bb169cf1c080'), ObjectId('654b8e929d16bb169cf1c082'), ObjectId('654b8e929d16bb169cf1c084'), ObjectId('654b8e929d16bb169cf1c086'), ObjectId('654b8e929d16bb169cf1c088'), ObjectId('654b8e929d16bb169cf1c08a'), ObjectId('654b8e929d16bb169cf1c08c'), ObjectId('654b8e929d16bb169cf1c094'), ObjectId('654b8e929d16bb169cf1c090'), ObjectId('654b8e929d16bb169cf1c092'), ObjectId('654b8e929d16bb169cf1c08e'), ObjectId('65804ba95dd8ec00e64298ae'), ObjectId('65804ba95dd8ec00e64298b0'), ObjectId('65b220d2acca0541e9d390d9'), ObjectId('65b220d2acca0541e9d390db'), ObjectId('65b220d2acca0541e9d390de'), ObjectId('65b220d2acca0541e9d390e0'), ObjectId('65b220d2acca0541e9d390e2'), ObjectId('65b220d2acca0541e9d390e4'), ObjectId('65b220d2acca0541e9d390e6'), ObjectId('65b220d2acca0541e9d390e8'), ObjectId('65b220d2acca0541e9d390ea'), ObjectId('65b220d2acca0541e9d390ec'), ObjectId('65e5cd126fcdf03f9046ba75'), ObjectId('65e5cd206fcdf03f9046ba7d'), ObjectId('65b0250dacca0541e9d2ba94'), ObjectId('65b0250dacca0541e9d2ba97'), ObjectId('65b0250dacca0541e9d2ba99'), ObjectId('65b0250dacca0541e9d2ba9b'), ObjectId('65b0250dacca0541e9d2ba9d'), ObjectId('65b0250dacca0541e9d2baa1'), ObjectId('65b0250dacca0541e9d2ba9f'), ObjectId('65b0250dacca0541e9d2baa3'), ObjectId('65b0250dacca0541e9d2baa5'), ObjectId('65b0250dacca0541e9d2baa7'), ObjectId('65b0250dacca0541e9d2baab'), ObjectId('65b0250dacca0541e9d2baa9'), ObjectId('65b0250dacca0541e9d2baaf'), ObjectId('65b0250dacca0541e9d2baad'), ObjectId('65b0250dacca0541e9d2bab1'), ObjectId('65b02513acca0541e9d2bb0a'), ObjectId('65b02513acca0541e9d2bb13'), ObjectId('65b02513acca0541e9d2bb15'), ObjectId('65b02513acca0541e9d2bb17'), ObjectId('65b02513acca0541e9d2bb19'), ObjectId('65b02513acca0541e9d2bb1b'), ObjectId('65b02513acca0541e9d2bb1d'), ObjectId('65b02514acca0541e9d2bb1f'), ObjectId('65b02514acca0541e9d2bb21'), ObjectId('65b02514acca0541e9d2bb23'), ObjectId('65b02514acca0541e9d2bb25'), ObjectId('65b02514acca0541e9d2bb29'), ObjectId('65b02514acca0541e9d2bb27'), ObjectId('65b02514acca0541e9d2bb2b'), ObjectId('65b02514acca0541e9d2bb2d'), ObjectId('65b02514acca0541e9d2bb2f'), ObjectId('65b02514acca0541e9d2bb35'), ObjectId('65b02514acca0541e9d2bb33'), ObjectId('65b02514acca0541e9d2bb31'), ObjectId('65b02514acca0541e9d2bb37'), ObjectId('65b02514acca0541e9d2bb3b'), ObjectId('65b02514acca0541e9d2bb39'), ObjectId('65b02514acca0541e9d2bb3d'), ObjectId('65b02514acca0541e9d2bb3f'), ObjectId('65b02514acca0541e9d2bb41'), ObjectId('65b02514acca0541e9d2bb43'), ObjectId('65b02514acca0541e9d2bb45'), ObjectId('65b02514acca0541e9d2bb47'), ObjectId('65b02514acca0541e9d2bb49'), ObjectId('65b02514acca0541e9d2bb4b'), ObjectId('65b02514acca0541e9d2bb4d'), ObjectId('65b02514acca0541e9d2bb4f'), ObjectId('65b02514acca0541e9d2bb51'), ObjectId('65b02514acca0541e9d2bb53'), ObjectId('65b02514acca0541e9d2bb57'), ObjectId('65b02514acca0541e9d2bb59'), ObjectId('65b02514acca0541e9d2bb55'), ObjectId('65b02514acca0541e9d2bb5b'), ObjectId('65b02514acca0541e9d2bb5d'), ObjectId('65b02514acca0541e9d2bb5f'), ObjectId('65b02514acca0541e9d2bb61'), ObjectId('65b02514acca0541e9d2bb63'), ObjectId('65b02514acca0541e9d2bb65'), ObjectId('65b02514acca0541e9d2bb69'), ObjectId('65b02514acca0541e9d2bb6b'), ObjectId('65b02514acca0541e9d2bb67'), ObjectId('65b21c7cacca0541e9d39075'), ObjectId('65b21c7cacca0541e9d39077'), ObjectId('65b21c7cacca0541e9d39079'), ObjectId('65b21c7cacca0541e9d3907c'), ObjectId('65b21c7cacca0541e9d3907e'), ObjectId('65b21c7cacca0541e9d39080'), ObjectId('65b21c7cacca0541e9d39082'), ObjectId('65b21c7cacca0541e9d39084'), ObjectId('65b21c7cacca0541e9d39086'), ObjectId('65b21c7cacca0541e9d39088'), ObjectId('65b21c7cacca0541e9d3908a'), ObjectId('65b21c7cacca0541e9d3908c'), ObjectId('65b21c7cacca0541e9d39090'), ObjectId('65b21c7cacca0541e9d39092'), ObjectId('65b21c7cacca0541e9d3908e'), ObjectId('65b220a9acca0541e9d390af'), ObjectId('65b220a9acca0541e9d390b1'), ObjectId('65b220a9acca0541e9d390b3'), ObjectId('65b220a9acca0541e9d390b6'), ObjectId('65b220a9acca0541e9d390b8'), ObjectId('65b220a9acca0541e9d390ba'), ObjectId('65b220a9acca0541e9d390bc'), ObjectId('65b220a9acca0541e9d390be'), ObjectId('65b220a9acca0541e9d390c0'), ObjectId('65b220a9acca0541e9d390c2'), ObjectId('66053524c0857387255f7d69'), ObjectId('66053524c0857387255f7d6b'), ObjectId('66053524c0857387255f7d6d'), ObjectId('66053524c0857387255f7d6f'), ObjectId('66053524c0857387255f7d67'), ObjectId('66053524c0857387255f7d71'), ObjectId('66053524c0857387255f7d73'), ObjectId('66053524c0857387255f7d75'), ObjectId('66053524c0857387255f7d77'), ObjectId('6605352bc0857387255f7d8a'), ObjectId('6605352bc0857387255f7d8c'), ObjectId('6605352bc0857387255f7d8e'), ObjectId('6605352bc0857387255f7d90'), ObjectId('6605352bc0857387255f7d92'), ObjectId('6605352bc0857387255f7d94'), ObjectId('6605352bc0857387255f7d97'), ObjectId('6605352bc0857387255f7d99'), ObjectId('66053532c0857387255f7dd2'), ObjectId('66053532c0857387255f7ddb'), ObjectId('66053532c0857387255f7ddd'), ObjectId('66053532c0857387255f7ddf'), ObjectId('66053532c0857387255f7de1'), ObjectId('66053532c0857387255f7de3'), ObjectId('66053532c0857387255f7de5'), ObjectId('66053532c0857387255f7de7'), ObjectId('66053532c0857387255f7de9'), ObjectId('66053532c0857387255f7deb'), ObjectId('66053532c0857387255f7ded'), ObjectId('66053532c0857387255f7df3'), ObjectId('66053532c0857387255f7def'), ObjectId('66053532c0857387255f7df5'), ObjectId('66053532c0857387255f7df9'), ObjectId('66053532c0857387255f7df7'), ObjectId('66053532c0857387255f7df1'), ObjectId('66053532c0857387255f7dfd'), ObjectId('66053532c0857387255f7dfb'), ObjectId('66053532c0857387255f7dff'), ObjectId('66053532c0857387255f7e01'), ObjectId('66053532c0857387255f7e03'), ObjectId('66053532c0857387255f7e05'), ObjectId('66053533c0857387255f7e09'), ObjectId('66053532c0857387255f7e07'), ObjectId('66053533c0857387255f7e0b'), ObjectId('66053533c0857387255f7e0d'), ObjectId('66053533c0857387255f7e11'), ObjectId('66053533c0857387255f7e0f'), ObjectId('66053533c0857387255f7e13'), ObjectId('6605353ac0857387255f7e3a'), ObjectId('6605353ac0857387255f7e3c'), ObjectId('6605353ac0857387255f7e3e'), ObjectId('6605353ac0857387255f7e45'), ObjectId('6605353ac0857387255f7e47'), ObjectId('6605353ac0857387255f7e49'), ObjectId('6605353ac0857387255f7e4b'), ObjectId('6605353ac0857387255f7e4d'), ObjectId('6605353ac0857387255f7e4f'), ObjectId('6605353ac0857387255f7e51'), ObjectId('6605353ac0857387255f7e53'), ObjectId('6605353ac0857387255f7e55'), ObjectId('6605353ac0857387255f7e57'), ObjectId('6605353ac0857387255f7e59'), ObjectId('6605353ac0857387255f7e5b'), ObjectId('6605353ac0857387255f7e5d'), ObjectId('6605353ac0857387255f7e5f'), ObjectId('6605353ac0857387255f7e61'), ObjectId('6605353ac0857387255f7e63'), ObjectId('6605353ac0857387255f7e65'), ObjectId('66053546c0857387255f7f18'), ObjectId('66053546c0857387255f7f1a'), ObjectId('66053546c0857387255f7f1c'), ObjectId('66053546c0857387255f7f1e'), ObjectId('66053546c0857387255f7f20'), ObjectId('66053546c0857387255f7f22'), ObjectId('66053546c0857387255f7f24'), ObjectId('66053546c0857387255f7f27'), ObjectId('66053546c0857387255f7f29'), ObjectId('66053546c0857387255f7f2b'), ObjectId('66053546c0857387255f7f2d'), ObjectId('66053546c0857387255f7f2f'), ObjectId('66053546c0857387255f7f31'), ObjectId('66053546c0857387255f7f33'), ObjectId('66053546c0857387255f7f35'), ObjectId('66053546c0857387255f7f37'), ObjectId('66053546c0857387255f7f39'), ObjectId('66053546c0857387255f7f3b'), ObjectId('66053546c0857387255f7f47'), ObjectId('66053546c0857387255f7f3d'), ObjectId('66053546c0857387255f7f3f'), ObjectId('66053546c0857387255f7f43'), ObjectId('66053546c0857387255f7f41'), ObjectId('66053546c0857387255f7f45'), ObjectId('66053546c0857387255f7f49'), ObjectId('66053546c0857387255f7f4b'), ObjectId('66053546c0857387255f7f4d'), ObjectId('66053546c0857387255f7f51'), ObjectId('66053546c0857387255f7f4f'), ObjectId('66053546c0857387255f7f53'), ObjectId('66053546c0857387255f7f55'), ObjectId('66053546c0857387255f7f57'), ObjectId('66053546c0857387255f7f59'), ObjectId('66053546c0857387255f7f5b'), ObjectId('66053546c0857387255f7f5d'), ObjectId('66053546c0857387255f7f5f'), ObjectId('66053546c0857387255f7f61'), ObjectId('66053546c0857387255f7f6d'), ObjectId('66053546c0857387255f7f6f'), ObjectId('66053546c0857387255f7f63'), ObjectId('66053546c0857387255f7f65'), ObjectId('66053546c0857387255f7f69'), ObjectId('66053546c0857387255f7f67'), ObjectId('66053546c0857387255f7f6b'), ObjectId('66053546c0857387255f7f73'), ObjectId('66053546c0857387255f7f71'), ObjectId('66053546c0857387255f7f75'), ObjectId('66053546c0857387255f7f77'), ObjectId('66053546c0857387255f7f79'), ObjectId('66053546c0857387255f7f7b'), ObjectId('66053546c0857387255f7f7d'), ObjectId('66053546c0857387255f7f7f'), ObjectId('66053546c0857387255f7f81'), ObjectId('66053546c0857387255f7f83'), ObjectId('66053546c0857387255f7f85'), ObjectId('66053546c0857387255f7f87'), ObjectId('66053546c0857387255f7f89'), ObjectId('66053546c0857387255f7f8b'), ObjectId('66053546c0857387255f7f8d'), ObjectId('66053546c0857387255f7f8f'), ObjectId('66053546c0857387255f7f91'), ObjectId('66053546c0857387255f7f93'), ObjectId('66053546c0857387255f7f99'), ObjectId('66053546c0857387255f7f95'), ObjectId('66053546c0857387255f7f97'), ObjectId('66053546c0857387255f7f9b'), ObjectId('66053546c0857387255f7f9d'), ObjectId('66053546c0857387255f7f9f'), ObjectId('66053546c0857387255f7fa1'), ObjectId('66053546c0857387255f7fa3'), ObjectId('66053546c0857387255f7fa7'), ObjectId('66053546c0857387255f7fa9'), ObjectId('66053546c0857387255f7fab'), ObjectId('66053546c0857387255f7fa5'), ObjectId('66053546c0857387255f7fad'), ObjectId('66053546c0857387255f7faf'), ObjectId('66053546c0857387255f7fb1'), ObjectId('66053546c0857387255f7fb3'), ObjectId('66053546c0857387255f7fb5'), ObjectId('66053546c0857387255f7fb7'), ObjectId('66053546c0857387255f7fb9'), ObjectId('66053546c0857387255f7fc1'), ObjectId('66053546c0857387255f7fbb'), ObjectId('66053546c0857387255f7fbd'), ObjectId('66053546c0857387255f7fbf'), ObjectId('66053546c0857387255f7fc5'), ObjectId('66053546c0857387255f7fc3'), ObjectId('66053546c0857387255f7fc7')]

In [4]:
%%time

df_basic_100 = pd.DataFrame()
collection = db['basic_analyses']
list_of_object_ids = reql[0:5]

for obj_id in list_of_object_ids:
    temp = {"testId": obj_id}
    cursor = collection.find(temp)
    
    df_basic = pd.DataFrame(list(cursor))
    
    df_basic_100 = pd.concat([df_basic_100, df_basic], ignore_index=True)

print(df_basic_100.head())
print(len(df_basic_100))

                        _id                    testId  \
0  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050
1  636a61b1c15659c370647c31  62c5cffe3a1ecea908c68050
2  641a8c7a2d5072a70ecaa7c2  62c5cffe3a1ecea908c68050
3  638f4acf9001555206371b1b  62c5cffe3a1ecea908c68050
4  639eeb7127ebaf8b671bd725  62c5cffe3a1ecea908c68050

                     userId  isBonusAttempted  \
0  618750829dac4fdd68eee09e             False
1  61a64eaa30edc6b02ba79a4f             False
2  62172150f579d177ed6ce43d             False
3  624485b3223a42aa689c7d26             False
4  6257b663e0d02d0349af4556             False

                                            sections  \
0  [{'_id': 6390364d69f7d5525911fe28, 'sectionId'...
1  [{'_id': 636a61b1c15659c370647c32, 'sectionId'...
2  [{'_id': 641a8c7a2d5072a70ecaa7c3, 'sectionId'...
3  [{'_id': 638f4acf9001555206371b1c, 'sectionId'...
4  [{'_id': 639eeb7127ebaf8b671bd726, 'sectionId'...

                                            subjects  totalTimeTaken  \
0  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444
1  [{'_id': 636a61b1c15659c370647c92, 'subjectId'...             370
2  [{'_id': 641a8c7a2d5072a70ecaa832, 'subjectId'...            2401
3  [{'_id': 638f4acf9001555206371ba9, 'subjectId'...           10602
4  [{'_id': 639eeb7127ebaf8b671bd7a5, 'subjectId'...            7195

   totalMarkScored  totalAttempted  totalCorrect   accuracy  \
0              139              46            37  80.434783
1               20              10             6  60.000000
2               25              15             8  53.333333
3              192              53            49  92.452830
4               35              35            14  40.000000

              submittedAt  __v
0 2022-12-07 06:44:29.224    0
1 2022-11-08 14:03:29.306    0
2 2023-03-22 05:04:58.804    0
3 2022-12-06 13:59:43.093    0
4 2022-12-18 10:29:05.967    0
1555
Wall time: 51.6 s

In [21]:
df=df_basic_100

In [22]:
df.columns

Index(['_id', 'testId', 'userId', 'sections', 'subjects', 'totalTimeTaken'], dtype='object')

In [38]:
# df.drop(columns=['totalMarkScored', 'totalAttempted', 'totalCorrect', 'accuracy', 'submittedAt', '__v','isBonusAttempted' ], inplace=True)

In [24]:
df

,_id,testId,userId,sections,subjects,totalTimeTaken
0,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,"[{'_id': 6390364d69f7d5525911fe28, 'sectionId'...","[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444
1,636a61b1c15659c370647c31,62c5cffe3a1ecea908c68050,61a64eaa30edc6b02ba79a4f,"[{'_id': 636a61b1c15659c370647c32, 'sectionId'...","[{'_id': 636a61b1c15659c370647c92, 'subjectId'...",370
2,641a8c7a2d5072a70ecaa7c2,62c5cffe3a1ecea908c68050,62172150f579d177ed6ce43d,"[{'_id': 641a8c7a2d5072a70ecaa7c3, 'sectionId'...","[{'_id': 641a8c7a2d5072a70ecaa832, 'subjectId'...",2401
3,638f4acf9001555206371b1b,62c5cffe3a1ecea908c68050,624485b3223a42aa689c7d26,"[{'_id': 638f4acf9001555206371b1c, 'sectionId'...","[{'_id': 638f4acf9001555206371ba9, 'subjectId'...",10602
4,639eeb7127ebaf8b671bd725,62c5cffe3a1ecea908c68050,6257b663e0d02d0349af4556,"[{'_id': 639eeb7127ebaf8b671bd726, 'sectionId'...","[{'_id': 639eeb7127ebaf8b671bd7a5, 'subjectId'...",7195
...,...,...,...,...,...,...
1550,642fb5ac7f9d938ee005a56e,62c5cffe3a1ecea908c68056,63e7aeaf0dd35d4508972c6d,"[{'_id': 642fb5ac7f9d938ee005a56f, 'sectionId'...","[{'_id': 642fb5ac7f9d938ee005a5da, 'subjectId'...",2273
1551,64316a67564841c22dbeab70,62c5cffe3a1ecea908c68056,63e88d3b7f592f4695d585af,"[{'_id': 64316a67564841c22dbeab71, 'sectionId'...","[{'_id': 64316a67564841c22dbeabff, 'subjectId'...",10036
1552,6405d53b061646a5fc8bed67,62c5cffe3a1ecea908c68056,63ec71fe2a281a458c630e3a,"[{'_id': 6405d53b061646a5fc8bed68, 'sectionId'...","[{'_id': 6405d53b061646a5fc8bedec, 'subjectId'...",10276
1553,64184ae11f0103a6ef628446,62c5cffe3a1ecea908c68056,63fb9f4a505355455ee15d5d,"[{'_id': 64184ae11f0103a6ef628447, 'sectionId'...","[{'_id': 64184ae11f0103a6ef6284d5, 'subjectId'...",7983
1554,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,"[{'_id': 6437c38b997e32c1796f5467, 'sectionId'...","[{'_id': 6437c38b997e32c1796f54c7, 'subjectId'...",3

In [25]:
df.columns

Index(['_id', 'testId', 'userId', 'sections', 'subjects', 'totalTimeTaken'], dtype='object')

In [41]:
len(df['userId'].unique())

957

In [63]:
# Initialize empty lists to store results
section_results = []
question_results = []
time_taken_results = []

# Iterate over each row in the DataFrame
for index, row in df.iterrows():
    sections = row['sections']
    
    # Iterate over sections
    for section in sections:
        questions = section['questions']
        
        # Iterate over questions in the section
        for question in questions:
            question_id = question['questionId']  # Extract '_id' instead of 'question'
            time_taken = question['timeTaken']
            
            # Append to results lists
            section_results.append(section['_id'])  # Assuming you want to keep the entire section for reference
            question_results.append(question_id)
            time_taken_results.append(time_taken)

# Create a new DataFrame with extracted data
result_df = pd.DataFrame({
    'Section': section_results,
    'Question ID': question_results,  # Renamed to 'Question ID' to reflect '_id' field
    'Time Taken': time_taken_results
})

print(result_df)

                         Section               Question ID  Time Taken
0       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac13          83
1       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac18          71
2       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac1d          52
3       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac22          44
4       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac27          64
...                          ...                       ...         ...
139945  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c14a           0
139946  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c14f           0
139947  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c154           0
139948  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c159           0
139949  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c15e           0

[139950 rows x 3 columns]

In [64]:
type(result_df)

pandas.core.frame.DataFrame

In [65]:
result_df

                         Section               Question ID  Time Taken
0       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac13          83
1       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac18          71
2       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac1d          52
3       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac22          44
4       6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac27          64
...                          ...                       ...         ...
139945  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c14a           0
139946  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c14f           0
139947  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c154           0
139948  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c159           0
139949  6437c38b997e32c1796f54bc  636a1ec7569ccaf8ef17c15e           0

[139950 rows x 3 columns]

In [66]:
result_df.head()

                    Section               Question ID  Time Taken
0  6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac13          83
1  6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac18          71
2  6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac1d          52
3  6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac22          44
4  6390364d69f7d5525911fe28  636a1ec1569ccaf8ef17ac27          64

In [72]:
rows = []
other_columns = []

for index, row in df.iterrows():
    _id = row['_id']
    testId = row['testId']
    userId = row['userId']
    subjects = row['subjects']
    totalTimeTaken = row['totalTimeTaken']
    
    sections = row['sections']
    
    for section in sections:
        section_id = section['_id']
        questions = section['questions']
        
        for question in questions:
            question_id = question['questionId']
            time_taken = question['timeTaken']
            
            rows.append({
                '_id': _id,
                'testId': testId,
                'userId': userId,
                'Section': section_id,
                'Question ID': question_id,
                'Time Taken': time_taken,
                'subjects': subjects,
                'totalTimeTaken': totalTimeTaken
            })
            other_columns.append({
                '_id': _id,
                'testId': testId,
                'userId': userId,
                'subjects': subjects,
                'totalTimeTaken': totalTimeTaken
            })

expanded_df = pd.DataFrame(rows)

for col in ['_id', 'testId', 'userId', 'subjects', 'totalTimeTaken']:
    expanded_df[col] = [data[col] for data in other_columns]

print("\nExpanded DataFrame:")
print(expanded_df.head())

Expanded DataFrame:
                        _id                    testId  \
0  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050
1  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050
2  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050
3  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050
4  6390364d69f7d5525911fe27  62c5cffe3a1ecea908c68050

                     userId                   Section  \
0  618750829dac4fdd68eee09e  6390364d69f7d5525911fe28
1  618750829dac4fdd68eee09e  6390364d69f7d5525911fe28
2  618750829dac4fdd68eee09e  6390364d69f7d5525911fe28
3  618750829dac4fdd68eee09e  6390364d69f7d5525911fe28
4  618750829dac4fdd68eee09e  6390364d69f7d5525911fe28

                Question ID  Time Taken  \
0  636a1ec1569ccaf8ef17ac13          83
1  636a1ec1569ccaf8ef17ac18          71
2  636a1ec1569ccaf8ef17ac1d          52
3  636a1ec1569ccaf8ef17ac22          44
4  636a1ec1569ccaf8ef17ac27          64

                                            subjects  totalTimeTaken
0  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444
1  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444
2  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444
3  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444
4  [{'_id': 6390364d69f7d5525911feab, 'subjectId'...            6444

In [73]:
df.columns

Index(['_id', 'testId', 'userId', 'sections', 'subjects', 'totalTimeTaken'], dtype='object')

In [58]:
# ques_df = db['questions']
# questions_df = pd.DataFrame(list(ques_df.find()))

In [81]:
unique_question_ids = expanded_df['Question ID'].unique().tolist()
unique_question_ids
len(unique_question_ids)

450

In [82]:
ques_collection = db['questions'] 
ques_query = {'_id': {'$in': unique_question_ids}}
projection = {'approximateTimeRequired': 1, '_id': 1}
questions_data = list(ques_collection.find(ques_query,projection))

# Convert questions_data into a DataFrame
questions_df = pd.DataFrame(questions_data)

In [83]:
questions_df

                          _id  approximateTimeRequired
0    636a1ec1569ccaf8ef17ac13                      120
1    636a1ec1569ccaf8ef17ac18                      210
2    636a1ec1569ccaf8ef17ac1d                      150
3    636a1ec1569ccaf8ef17ac22                       90
4    636a1ec1569ccaf8ef17ac27                      120
..                        ...                      ...
445  636a1ec7569ccaf8ef17c14a                      120
446  636a1ec7569ccaf8ef17c14f                      210
447  636a1ec7569ccaf8ef17c154                      180
448  636a1ec7569ccaf8ef17c159                      180
449  636a1ec7569ccaf8ef17c15e                      120

[450 rows x 2 columns]

In [84]:
questions_df.rename(columns={'_id': 'Question ID'}, inplace=True)

In [85]:
merged_df = pd.merge(expanded_df, questions_df, on='Question ID', how='left')

In [87]:
merged_df.head()

,_id,testId,userId,Section,Question ID,Time Taken,subjects,totalTimeTaken,approximateTimeRequired
0,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac13,83,"[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444,120
1,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac18,71,"[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444,210
2,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac1d,52,"[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444,150
3,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac22,44,"[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444,90
4,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac27,64,"[{'_id': 6390364d69f7d5525911feab, 'subjectId'...",6444,120

In [90]:
merged_df.rename(columns={'totalTimeTaken': 'Total Time spent on Section'}, inplace=True)
merged_df.drop(columns = ['subjects'], inplace=True)

In [91]:
merged_df

,_id,testId,userId,Section,Question ID,Time Taken,Total Time spent on Section,approximateTimeRequired
0,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac13,83,6444,120
1,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac18,71,6444,210
2,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac1d,52,6444,150
3,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac22,44,6444,90
4,6390364d69f7d5525911fe27,62c5cffe3a1ecea908c68050,618750829dac4fdd68eee09e,6390364d69f7d5525911fe28,636a1ec1569ccaf8ef17ac27,64,6444,120
...,...,...,...,...,...,...,...,...
139945,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,6437c38b997e32c1796f54bc,636a1ec7569ccaf8ef17c14a,0,3,120
139946,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,6437c38b997e32c1796f54bc,636a1ec7569ccaf8ef17c14f,0,3,210
139947,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,6437c38b997e32c1796f54bc,636a1ec7569ccaf8ef17c154,0,3,180
139948,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,6437c38b997e32c1796f54bc,636a1ec7569ccaf8ef17c159,0,3,180
139949,6437c38b997e32c1796f5466,62c5cffe3a1ecea908c68056,63fe214d17ad8345c2c5614d,6437c38b997e32c1796f54bc,636a1ec7569ccaf8ef17c15e,0,3,120